### PR TITLE
Simplify PHPStan configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
### All Submissions:

* [x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### CODE REVIEW

**Comment by mscurtescu** [comment]
Thanks again @szepeviktor 

Merging here on `dev`, will later merge into `main`.

**Comment by mscurtescu** [comment]
Hi @szepeviktor ,

I finally merged your simplification into `main` and started using it, thanks again.

Running into an issue with phpstan that I cannot figure, as far as I can tell it properly pulls in the WordPress stubs but it seems to be confused about number of parameters:
```
  236    Function site_url invoked with 1 parameter, 0 required.   
  337    Function admin_url invoked with 1 parameter, 0 required.  
  573    Function get_bloginfo invoked with 1 parameter, 0 required.                           
  574    Function esc_attr invoked with 1 parameter, 0 required.                               
```

It's not complaining about all WordPress functions, only some.

For now I am ignoring these specific errors so I can see the real issues being brought up.

Any idea where is this coming from? Some extra libraries being imported unnecessarily? Thanks in advance

**Comment by szepeviktor** [comment]
Investigating 🏃🏻‍♂️

**Comment by szepeviktor** [comment]
On PHP 7.4 I get
```
 -- -----------------------------------------------------------------------------------------------------------
     Error
 -- -----------------------------------------------------------------------------------------------------------
     Ignored error pattern #^Function [^ ]+ invoked with [1234] parameters?, 0 required\.$# was not matched in
     reported errors.
 -- -----------------------------------------------------------------------------------------------------------
```

**Comment by mscurtescu** [comment]
I was getting the errors when running locally, either:
```shell
grunt shell:phpstan
```

or directly:
```shell
./vendor/bin/phpstan analyze
```

**Comment by szepeviktor** [comment]
Try cleaning composer cache, removing `vendor/` and doing a `composer update`.

**Comment by mscurtescu** [comment]
clearing the cache made no difference :-(

**Comment by szepeviktor** [comment]
All right.
All I can see it static analysis here on GitHub Actions recognizes those functions.

**Comment by mscurtescu** [comment]
Thanks, your help is much appreciated. Will try on a different computer with a clean state.

**Comment by mscurtescu** [comment]
On a clean computer it works as expected, thanks for your help. Yes, I have to figure what exactly is messing with phpstan.

**Comment by mscurtescu** [comment]
Really puzzling, still running into this error on one computer:

- run `./vendor/bin/phpstan clear-result-cache` (this is not documented when running `phpstan -h`)
- run `composer clear-cache`
- brand new git clone in a new folder

Since I am seeing the error in a brand new git clone the cause must reside outside of the git repo folder. Beyond phpstand and composer caches not sure what it can be. I also nuked the `npm` cache, but I don't see how that would be related anyhow.

Also, using `--debug` with `phpstan` is not providing much insight, it only shows what files are being analysed and what configuration file was used. Where are the WordPress stubs loaded from? I assume through `composer` from the `vendor` subfolder, but deleting that folder made no difference.

**Comment by szepeviktor** [comment]
> Where are the WordPress stubs loaded from?

From the extension's configuration: https://github.com/szepeviktor/phpstan-wordpress/blob/master/extension.neon#L116

**Comment by mscurtescu** [comment]
> > Where are the WordPress stubs loaded from?
> 
> From the extension's configuration: https://github.com/szepeviktor/phpstan-wordpress/blob/master/extension.neon#L116

So that's under `vendor`, a brand new git clone, or removing the `vendor` folder, should take care of a bad cache, and that's not the case. Is there any chance that stubs are also loaded from some other location?

**Comment by szepeviktor** [comment]
> Is there any chance that stubs are also loaded from some other location?

No, it is loaded from the extension.

**Comment by mscurtescu** [comment]
Maybe I am looking at it the wrong way and it's not a caching issue, what would generate an error like:

> Function admin_url invoked with 1 parameter, 0 required

How does phpstan determine that admin_url requires 0 parameters? I checked the stub and the stub has the expected signature which is:
```php
function admin_url($path = '', $scheme = 'admin')
{
}
```

**Comment by szepeviktor** [comment]
Search for `function admin_url` in every file.
`grep -rFn 'function admin_url'`
If there is another definition than that is the cause.
Otherwise it is a PHPStan error.

**Comment by mscurtescu** [comment]
```shell
$ find . -name \*.php -exec grep -iHn "function admin_url" {} \;
./vendor/php-stubs/wordpress-stubs/wordpress-stubs.php:110462:    function admin_url($path = '', $scheme = 'admin')
./wordpress/wp-includes/link-template.php:3522:function admin_url( $path = '', $scheme = 'admin' ) {
./wordpress/wp-admin/includes/noop.php:80:function admin_url() {}
```

This is the suspicious one: `./wordpress/wp-admin/includes/noop.php:80:function admin_url() {}`

I deleted the whole `wordpress` folder, now phpstan runs as expected.

Questions:

1. Why is phpstan loading this folder?
2. Checking what is different on my other computer where it worked from the beginning...

**Comment by mscurtescu** [comment]
Answering question 2, on the machine where phpstan worked, there is also the exact same `./wordpress/wp-admin/includes/noop.php:80:function admin_url() {}`, mind bugling

**Comment by szepeviktor** [comment]
PHPStan should be instructed to scan that file in `phpstan.neon.dist`

**Comment by szepeviktor** [comment]
Here is our perpetrator!!!
https://github.com/hellocoop/wordpress/blob/e84227688bfe17b5c859882d67bd0b5616f78f05/composer.json#L65

**Comment by mscurtescu** [comment]
The content of `phpstan.neon.dist`:

```yaml
parameters:
  level: 5
  inferPrivatePropertyTypeFromConstructor: true
  bootstrapFiles:
    - tests/phpstan-bootstrap.php
  paths:
    - hello-login.php
    - includes/
```

**Comment by szepeviktor** [comment]
The cause is in the previous comment!

**Comment by mscurtescu** [comment]
> Here is our perpetrator!!!
> 
> https://github.com/hellocoop/wordpress/blob/e84227688bfe17b5c859882d67bd0b5616f78f05/composer.json#L65

So on some machines classes are loaded in some order and on other machines in a different one?

**Comment by szepeviktor** [comment]
> So on some machines classes are loaded in some order and on other machines in a different one?

- composer install
- composer install --no-dev

That makes the difference.

**Comment by mscurtescu** [comment]
> The cause is in the previous comment!

Yes, removing `autoload-dev` for now, it was inherited from the parent project (the one this project forked). Thanks.

**Comment by mscurtescu** [comment]
> > So on some machines classes are loaded in some order and on other machines in a different one?
> 
> * composer install
> * composer install --no-dev
> 
> That makes the difference.

I don't think it's that, running `composer install --no-dev` will not download and install the `wordpress` folder, that definitely helps. but on my other machine the `wordpress` folder was installed and it still works, so it must be class loading order.

**Comment by mscurtescu** [comment]
adding:
```yaml
  excludePaths:
  	- wordpress/
```

also works, yay!

**Comment by mscurtescu** [comment]
köszönöm szépen

**Pull request merged**
